#!/usr/bin/env bash
#
# Interactive Deployment Wizard for ZenFX (Supabase, Vercel, & GCP Cloud Run)
# Generated by the /wizard skill.
#

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=3
TOTAL_MINUTES=15

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env.local}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  Wizard ini menuntun Anda langkah demi langkah untuk mengonfigurasi\n' "$DIM"
  printf '  Supabase Auth, Vercel Deployment, dan Google Cloud Run (GCP).\n'
  printf '  Tekan Ctrl-C kapan saja untuk berhenti dan melanjutkan nanti.%s\n\n' "$RESET"
  pause "Siap untuk memulai?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Tahap %s/%s · %s%s  %s(~%s min tersisa)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ membuka%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "Gagal membuka browser — buka manual: $url"; fi
  } >/dev/null 2>&1 || warn "Gagal membuka browser — buka manual: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Tekan Enter untuk melanjutkan}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter menggunakan nilai yang ada]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter menggunakan nilai yang ada]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ tersimpan%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Konfigurasi ZenFX Selesai!%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} )) && note "Berhasil menyimpan ${#WRITTEN_ENV[@]} variabel ke $ENV_FILE: ${WRITTEN_ENV[*]}"
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Authoring Setup
# ──────────────────────────────────────────────────────────────────────────

banner "ZenFX Deployment Wizard (Supabase + Vercel + GCP)"

# ── STAGE 1: SUPABASE SETUP ─────────────────────────────────────────────
stage "Supabase — Database & Authentication" 5
say "Kita akan mengambil Kredensial Supabase untuk Auth & Database."
open_url "https://supabase.com/dashboard"
step "1. Klik 'New Project' -> Masukkan nama 'zenfx-db', buat password, pilih region Singapore."
step "2. Buka Project Settings (ikon gerigi) -> API."
step "3. Salin Project URL (dimulai dengan https://...supabase.co)."
ask NEXT_PUBLIC_SUPABASE_URL "Tempelkan NEXT_PUBLIC_SUPABASE_URL:"

step "4. Salin anon / public key (kunci publik panjang)."
ask_secret NEXT_PUBLIC_SUPABASE_ANON_KEY "Tempelkan NEXT_PUBLIC_SUPABASE_ANON_KEY:"

write_env NEXT_PUBLIC_SUPABASE_URL "https://hjpcmlhmoxhymstdtnve.supabase.co"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqcGNtbGhtb3hoeW1zdGR0bnZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU4NDQyNjEsImV4cCI6MjEwMTQyMDI2MX0.0bXaMlSt5q6hD-YulSjw8giLjBd3qm__zMt3oqQMJc4"

step "5. Buka Authentication -> Users -> Add User -> Create User untuk membuat akun email & password pribadi Anda/Mentor."
pause "Sudah membuat akun User di Supabase?"

# ── STAGE 2: VERCEL SETUP ───────────────────────────────────────────────
stage "Vercel — Instant Hosting Deployment" 4
say "Kita akan medeploy ZenFX ke Vercel secara instant."
open_url "https://vercel.com/new"
step "1. Import repositori GitHub 'ZenFX'."
step "2. Di seksi Environment Variables, masukkan variabel dari .env.local:"
note "   - FINNHUB_API_KEY"
note "   - GROQ_API_KEY"
note "   - FRED_API_KEY"
note "   - NEXT_PUBLIC_SUPABASE_URL"
note "   - NEXT_PUBLIC_SUPABASE_ANON_KEY"
step "3. Klik Deploy!"
ask VERCEL_PROJECT_URL "Tempelkan URL Vercel yang dihasilkan (misal https://zenfx.vercel.app):"
write_env VERCEL_PROJECT_URL "$VERCEL_PROJECT_URL"

# ── STAGE 3: GOOGLE CLOUD RUN (GCP) SETUP ───────────────────────────────
stage "Google Cloud Run — Enterprise Container Deployment" 6
say "Kita akan menyiapkan Google Cloud Run untuk opsi hosting GCP."
open_url "https://console.cloud.google.com"
step "1. Buat project baru bernama 'zenfx-production' di GCP Console."
ask GCP_PROJECT_ID "Masukkan GCP Project ID Anda:"

step "2. Jalankan perintah berikut di terminal komputer Anda:"
note "   gcloud artifacts repositories create zenfx-repo --repository-format=docker --location=asia-southeast1"
note "   gcloud builds submit --tag asia-southeast1-docker.pkg.dev/$GCP_PROJECT_ID/zenfx-repo/zenfx-app:v1 ."
note "   gcloud run deploy zenfx-app --image asia-southeast1-docker.pkg.dev/$GCP_PROJECT_ID/zenfx-repo/zenfx-app:v1 --region asia-southeast1 --allow-unauthenticated"

ask GCP_CLOUD_RUN_URL "Tempelkan URL GCP Cloud Run yang dihasilkan:"
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
write_env GCP_CLOUD_RUN_URL "$GCP_CLOUD_RUN_URL"

finish
